### PR TITLE
feat: adds support for base network

### PR DESCRIPTION
**Pull request by meetkosiso**
## Checklist

- [ ] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

### CODE REVIEW

**Comment by wpoulin** [comment]
Could you not delete the `pnpm-lock` file 🙏

**Comment by meetkosiso** [comment]
> Could you not delete the `pnpm-lock` file 🙏

Not deleting the `pnpm-lock` file is failing the build checks. I tried severally not to delete the file and on each occasion, the build test failed after committing.

**Review by wpoulin — CHANGES_REQUESTED** [review]
There has to be something wrong with your `pnpm-lock.yaml`. Have you tried hard resetting the file to master's version

**Comment by meetkosiso** [comment]
> There has to be something wrong with your `pnpm-lock.yaml`. Have you tried hard resetting the file to master's version

Yes, I tried resetting it from the master, same experience, and also I did not add any new dependency, I only pull the latest changes that contains some new dependencies  and did `pnpm install` to install the dependency and when I committed my changes,  the commit is failing because of  `pnpm-lock.yaml`.

**Comment by wpoulin** [comment]
Initially, I think there was something wrong with your fork as CI never ran on the PRs you opened on Studio. I always had to merge without waiting for requirements (aka skip CI steps ) 
Have you considered deleting and forking again making sure everything is up to date ?

**Comment by meetkosiso** [comment]
> Initially, I think there was something wrong with your fork as CI never ran on the PRs you opened on Studio. I always had to merge without waiting for requirements (aka skip CI steps ) Have you considered deleting and forking again making sure everything is up to date ?

I have fixed the `pnp-lock` file issue and it ran successfully on the CI. Thanks.

**Review by wpoulin — APPROVED** [review]

**Comment by wpoulin** [comment]
Adding remote upstream, get the latest changes from the upstream to your branch  and push. This will resolve the issue  `This branch is out-of-date with the base branch`

**Comment by meetkosiso** [comment]
> Adding remote upstream, get the latest changes from the upstream to your branch, and push. This will resolve the issue `This branch is out-of-date with the base branch`

Thanks @wpoulin, yes I'm adding `upstream`, this issue was because of I had a different version of `pnpm`. Could you review and possibly merge? Thanks.

**Comment by wpoulin** [comment]
Well done, BINGO !!!!

**Pull request merged**
