### PR TITLE
refactor: adds support to use good-ghosting endpoint to get user balances

### PR DESCRIPTION
**Pull request by meetkosiso**
## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

### CODE REVIEW

**Review by immasandwich — APPROVED** [review]

**Comment by immasandwich** [comment]
I've approved the changes @meetkosiso , but this will make doing historical balances harder (in the future). Using on-chain requests, we can send a block number to get a user's balances at a given point in time using an archival node. This is not possible by using the API endpoint.

Ideally, try to use on-chain RPC calls for balances as much as possible so that we can compute historical balances easier in the future!

**Comment by meetkosiso** [comment]
> I've approved the changes @meetkosiso , but this will make doing historical balances harder (in the future). Using on-chain requests, we can send a block number to get a user's balances at a given point in time using an archival node. This is not possible by using the API endpoint.
> 
> Ideally, try to use on-chain RPC calls for balances as much as possible so that we can compute historical balances easier in the future!

Thank you @immasandwich. We made the decision to migrate to our endpoint because our current integration was returning an incorrect user balance, and there are lots of external calls and logic required to correctly compute a user balance, moving that over to Zapper,  will be like writing most of our core logic, aside that we are at the verge of releasing any version of our Protocol, this version is entirely different from what we currently support, and we are meant to support both versions. We figure out that the most viable way to support both versions on Zapper is moving our integration to use our backend since our backend will support both versions. We might re-visit this in the future, but at the moment we feel that moving the integration to our backend will be the most viable way to return the correct balances to our user and also support our protocol V2. 

Thanks.

**Comment by SamIam-0x** [comment]
Hello @meetkosiso ! 

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by SamIam-0x** [comment]
Gentle ping on the above @meetkosiso ! Thanks!

**Pull request merged**
