### PR TITLE
feat(teahouse): Add token-fetcher for Teahouse vault on Arbitrum.

### PR DESCRIPTION
**Pull request by ajak1124**
## Description

Add token-fetcher for Teahouse vault on Arbitrum.

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

## How to test?

test address 0x9f4fff022ebff0cbfa3faf702911d0f658a4ba9b
price per token should be : 0.999921
token balance of test address : 98232.357552
token balance in USD of test address : 98224.59719575339

### CODE REVIEW

**Comment by wpoulin** [comment]
Can you remove changes made to `yarn.lock` and `package-lock.json`, plus, could you also resolve conflicts in `teahouse.module`

**Comment by ajak1124** [comment]
Hi, how about i delete  yarn.lock and package-lock.json ? and already resolved conflicts in teahouse.module.

**Comment by wpoulin** [comment]
I don't know where the changes in `yarn.lock` and `package-lock.json` are coming from. You haven't added any packages, so these files should stay the same. You can do as you wish to remove the changes as long as the files are the same

**Comment by ajak1124** [comment]
Hi, I already delete yarn-lock.json and reinstall package.json, pls try again, thanks.

**Comment by wpoulin** [comment]
It's not about deleting the files, it's about reverting the changes you've done the these 2 files. Both files are useful and we want to keep both as they were prior

**Pull request closed without merging**
