### PR TITLE
feat(diffusion-protocol): Diff integration (#2)

### PR DESCRIPTION
**Pull request by scruffy-dev**
## Description
Added diffusion to studio. Btw awesome CLI tool real easy to use thank you 

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

### CODE REVIEW

**Comment by immasandwich** [comment]
Hey @scruffy-dev ! Thanks for contributing. You'll likely find [this recipe](https://studio.zapper.fi/docs/recipes/uniswap-v2-fork-pool-token) quite useful for integrating pools, [this one](https://studio.zapper.fi/docs/recipes/master-chef-farm) for your farms, and [this one](https://studio.zapper.fi/docs/recipes/vault-token) for xDIFF.

Glad to discuss further in Discord!

**Comment by scruffy-dev** [comment]
very cool, the only issue is that the get position requires the graph which is not yet supported on evmos. Can we merge this in as is and then I can add the recipes when all dependencies are supported

**Comment by immasandwich** [comment]
@scruffy-dev Sure that shouldn't be a problem. You can also rely on the `UniswapV2OnChainPoolTokenAddressStrategy` described [here](https://studio.zapper.fi/docs/recipes/uniswap-v2-fork-pool-token#add-resolvepooltokenaddresses-parameter) to retrieve pool addresses from the factory contract (rather than TheGraph), pointing to `0x6aBdDa34Fb225be4610a2d153845e09429523Cd2` as your factory contract.

```
resolvePoolTokenAddresses: this.uniswapV2OnChainPoolTokenAddressStrategy.build({
  resolvePoolsLength: ({ multicall, factoryContract }) => multicall.wrap(factoryContract).allPairsLength(),
  resolvePoolAddress: ({ multicall, factoryContract, poolIndex }) =>
    multicall.wrap(factoryContract).allPairs(poolIndex),
  }),
```

This will resolve 301 pairs currently.

**Comment by scruffy-dev** [comment]
hey thanks for the heads up, I was able to add the token fetcher, will circle back to the master chef when I get more time next week, If is cool and this PR works I am ok with merging it now and creating a separate PR.

**Comment by immasandwich** [comment]
@scruffy-dev Looks good to me. The balances will work by default, so we can get this merged now and circle back for the master chef later.

**Comment by SamIam-0x** [comment]
Hello @scruffy-dev !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by SamIam-0x** [comment]
Gentle ping on this @scruffy-dev ! This is a real message from a person at Zapper!

**Pull request merged**
