### PR TITLE
feat: Rocket Pool

### PR DESCRIPTION
**Pull request by peteriscan**
## Description

This adds support for Rocket Pool. It's a decentralized Ethereum staking protocol.

Rocket Pool token is RPL and the liquid staking token is rETH.

There are two RPL tokens: old one and new one. Old RPL has a fixed supply of 18m tokens. It's known as Old RPL, RPL Legacy, RPLv1. The new RPL token is inflationary. It's known as RPL or RPLv2. You can migrate RPLv1 to RPLv2 for 1:1.

RPL can be staked by node operators. RPL is also bonded by Oracle DAO members.

rETH is minted on Ethereum but has been bridged to Arbitrum, Optimism, Polygon.

Rocket Pool shows the tokens in two groups: `Rocket Pool Protocol Token` and `Rocket Pool ETH`. `Rocket Pool Protocol Token` shows RPL in the wallet (both RPLv1 and RPLv2) as well as staked RPL and bonded RPL balances.

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)

## How to test?

Test these addresses and compare the values on Rocketscan:

* rETH on Ethereum, Arbitrum, Optimism: https://rocketscan.io/address/rocketscan.eth
* RPLv2 only https://rocketscan.io/address/0xfe4f7c242e030222c4ac4cc16e991d01c14d3fe0
* RPLv1 only https://rocketscan.io/address/0xb18a84980c009a2f958cf3db1bad7b592613c45c
* RPLv1 and RPLv2 https://rocketscan.io/address/0x702cacafa54b88e9c54449563fb2e496e85c78b7
* Node operator with staked RPL https://rocketscan.io/node/0x17fa597cec16ab63a7ca00fb351eb4b29ffa6f46
* Oracle DAO member with bonded RPL https://rocketscan.io/address/0xd7f94c53691afb5a616c6af96e7075c1ffa1d8ee
* Node operator & Oracle DAO member https://rocketscan.io/address/0x751683968fd078341c48b90bc657d6babc2339f7

### CODE REVIEW

**Comment by immasandwich** [comment]
A bit overwhelmed with the PRs right now, thanks for your patience ser 🙏

**Comment by immasandwich** [comment]
Hey @peteriscan sorry for the long delay, I'm gonna get this merged, but I see we have some duplicate balances (i.e.: rETH and RPL should already display in Zapper as base tokens in your Wallet section). As such, I'll remove the duplicate positions after the merge.

**Comment by SamIam-0x** [comment]
Hello @peteriscan & @volt62 !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by peteriscan** [comment]
@SamIam-0x `rocketscan.eth`

**Pull request merged**
