### PR TITLE
feat(qi-dao): add optimism support

### PR DESCRIPTION
**Pull request by the-emerald**
## Description
Add support for QiDAO on Optimism.

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] (optional) As a contributor, my Twitter handle is: th3_emerald

## How to test?

This is a copy-paste of the Arbitrum config but with Optimism addresses.

### CODE REVIEW

**Review by immasandwich — APPROVED** [review]

**Comment by SamIam-0x** [comment]
Hello @the-emerald !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by SamIam-0x** [comment]
Gentle ping on the above @the-emerald !

**Comment by the-emerald** [comment]
Ah, this one slipped by me, sorry! What's your discord username? I'll send you a DM.

**Comment by SamIam-0x** [comment]
Just sent you an FR on Discord

**Pull request merged**
