### PR TITLE
feat(wombat): Add Wombat Exchange integration

### PR DESCRIPTION
**Pull request by corey-wombat**
## Description

Add integration support for https://wombat.exchange/

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

### CODE REVIEW

**Comment by immasandwich** [comment]
Sorry for the delays ser. I'll try to get to this by tomorrow!

**Review by immasandwich — APPROVED** [review]
Nailed it! Sorry for the delays again 🙏

**Comment by SamIam-0x** [comment]
Hello @corey-wombat ! Zapper DeFi PM here-- Great work on this integration!

Not sure if you're aware, but when building an integration, Wombat Exchange also has its on app page on Zapper now, linked here: https://zapper.fi/apps/wombat-exchange?network=binance-smart-chain

It looks good as-is, but one thing to call out is some apps will add in APYs / APRs as data props in the integration to populate them alongside the assets on the app's page. We believe adding context like this helps users who may not know much about Wombat Exchange to get a better idea of the assets offered. An example of how it looks is Curve's page: https://zapper.fi/apps/curve?network=ethereum&appPrimaryGroup=Pools&page=1. APYs and other stats will also show up as details when a user looks at their Wombat balances.

Details on how to add them to the integration can be found here: https://studio.zapper.fi/docs/concepts/app-tokens#what-are-data-props

Just wanted to call it out in case that was of interest! Thanks for building this out!

**Comment by SamIam-0x** [comment]
Hello @corey-wombat  - thanks for submitting this! 

qq- do you have an ENS or address you'd want us to attribute this contribution to? We are building out a leaderboard to give credit to users who contributed to Zapper, with potential bonus points of value in the future.

Let me know, thanks!
Sam

**Pull request merged**
