### PR TITLE
fix(yield-protocol): use new subgraph Account entity reference

### PR DESCRIPTION
**Pull request by marcomariscal**
## Description

Yield Protocol `balance fetcher` changes in both ethereum and arbitrum:

Updates `vaultOwner` to `account` when referencing borrow balance-related subgraph data. We made some changes to our subgraph, where we added an `account` entity that now has `vaults`. 

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)

## How to test?

`0x3250e201c2eb06d086138f181e0fb6d1fe33f7d1` should have a vault on ethereum.

### CODE REVIEW

**Comment by marcomariscal** [comment]
@immasandwich, simple naming change here, but seems like I'm running into errors in dev (getting errors when fetching borrow balance data); wondering if you can take a look. 

Looks like i'm also getting caching errors as well in dev, and not sure if that's why I can't pull in the borrow balance data.

**Comment by immasandwich** [comment]
Absolutely will check tomorrow @marcomariscal ! Thanks for following up with the quick change 🙏

**Comment by immasandwich** [comment]
@marcomariscal looks ok to me with the addresses posted for testing here: https://github.com/Zapper-fi/studio/pull/562

and I'm not seeing any errors in local:
image

Can you give me more context of the errors you're seeing? For now, I'll go ahead and merge this since its looking good on my end.

**Comment by marcomariscal** [comment]
@immasandwich, ah great thank you!

Was seeing these types of errors:

Screen Shot 2022-07-16 at 8 06 18 AM

**Comment by SamIam-0x** [comment]
Hello @marcomariscal !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by SamIam-0x** [comment]
Gentle ping on the above @marcomariscal ! Thanks!

**Pull request merged**
