### PR TITLE
feat(sideshift): add sideshift

### PR DESCRIPTION
**Pull request by abrkn**
## Description

This adds the sideshift module for https://sideshift.ai and defines its svXAI (ERC-4626 compatible) staking vault token.

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

## How to test?

Open http://localhost:5001/apps/sideshift/tokens?groupIds[]=svxai with `ENABLED_APPS` set to `sideshift`

### CODE REVIEW

**Comment by wpoulin** [comment]
In order for Unit test to pass, you will need to add a `logo.png` under `/assets`

**Comment by abrkn** [comment]
@wpoulin I have added a logo as requested

**Review by wpoulin — APPROVED** [review]

**Comment by abrkn** [comment]
Thanks for the timely review and merge, @wpoulin 🎅🏻

**Comment by SamIam-0x** [comment]
Hello @abrkn  - thanks for submitting this! 

qq- do you have an ENS or address you'd want us to attribute this contribution to? We are building out a leaderboard to give credit to users who contributed to Zapper, with potential bonus points of value in the future.

Let me know, thanks!
Sam

**Comment by abrkn** [comment]
> Hello @abrkn - thanks for submitting this!
> 
> qq- do you have an ENS or address you'd want us to attribute this contribution to? We are building out a leaderboard to give credit to users who contributed to Zapper, with potential bonus points of value in the future.
> 
> Let me know, thanks! Sam

My personal is `brekken.eth`, you can use that 😄

**Comment by SamIam-0x** [comment]
Thanks!

**Pull request merged**
