### PR TITLE
feat(furucombo): add furucombo app module

### PR DESCRIPTION
**Pull request by dinngodev**
## Description

This PR adds a new app module, `furucombo`, for [Furucombo](https://furucombo.app/) on Polygon.

This app defines four groups:

- Furucombo Funds: fund

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] (optional) As a contributor, my Twitter handle is: [furucombo](https://twitter.com/furucombo)

## How to test?

- [Fund Token Featcher](http://localhost:5001/apps/furucombo/tokens?groupIds[]=fund&network=polygon)
- [Balance Fetcher](http://localhost:5001/apps/furucombo/balances?addresses%5B%5D=0xa3C1C91403F0026b9dd086882aDbC8Cdbc3b3cfB&network=polygon)

### CODE REVIEW

**Comment by immasandwich** [comment]
@dinngodev you're amazing. Great PR, that work you did on the token fetcher is _exactly_ the new pattern we're going for.

**Comment by chouandy** [comment]
Hi @immasandwich,
I found our balance fetcher has been removed in commit: [8ae191ec560c1b3f44c7e30ebb885ef4cf203030](https://github.com/Zapper-fi/studio/commit/8ae191ec560c1b3f44c7e30ebb885ef4cf203030)
If there is a problem with the code or if something went wrong?

**Comment by SamIam-0x** [comment]
@chouandy -- I'm following up on this now!

and @dinngodev !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by chouandy** [comment]
Hi @SamIam-0x,
Thanks for your reply. The following is the public address of our company.
Ethereum: 0xe4F15a5ed3150c27bE51816D68ca921fE8b2eD8d
polygon: 0x5cF829F5A8941f4CD2dD104e39486a69611CD013
So will the commit [8ae191ec560c1b3f44c7e30ebb885ef4cf203030](https://github.com/Zapper-fi/studio/commit/8ae191ec560c1b3f44c7e30ebb885ef4cf203030)  be reverted? or I submit a PR?

BR
Andy

**Comment by chouandy** [comment]
@immasandwich Got it. Thanks a lot~

**Pull request merged**
