### PR TITLE
feat(pooltogether): PoolTogether V5 Optimism Support

### PR DESCRIPTION
**Pull request by Ncookiez**
## Description

Added support for PoolTogether V5 prize vaults on Optimism. Made it super easy for future PRs to add support for other networks or more vaults.

This implementation is mostly done through the ERC4626 template provided, with a few minor changes to `getPricePerShare`, `getLabel` and `getLabelDetailed`, while also making it support multiple vaults, instead of just one.

## Checklist

- [x] I have followed the [Contributing Guidelines](https://github.com/Zapper-fi/studio/blob/main/CONTRIBUTING.md)
- [x] (optional) As a contributor, my Ethereum address/ENS is: `ncookie.eth`
- [x] (optional) As a contributor, my Twitter handle is: `@ncookie_eth` (`ncookie or ncookie.eth` on Farcaster)

## How to test?

Feel free to test with any wallet holding any the following tokens:

- [`0xE3B3a464ee575E8E25D2508918383b89c832f275`](https://optimistic.etherscan.io/token/0xE3B3a464ee575E8E25D2508918383b89c832f275#balances) (Prize USDC.e - Aave)
- [`0x29Cb69D4780B53c1e5CD4D2B817142D2e9890715`](https://optimistic.etherscan.io/token/0x29Cb69D4780B53c1e5CD4D2B817142D2e9890715#balances) (Prize WETH - Aave)
- [`0xCe8293f586091d48A0cE761bBf85D5bCAa1B8d2b`](https://optimistic.etherscan.io/token/0xCe8293f586091d48A0cE761bBf85D5bCAa1B8d2b#balances) (Prize DAI - Aave)

## Notes

This is my first contribution to this repo, so please do let me know if I did anything incorrectly. :3

A couple notes/feedback from a first-timer:

- There are many references to `create-group` in the docs, which were a bit confusing to me until I realized it was recently removed.
- The token fetcher template generated seems to set the `appToolkit` as `private` instead of `protected`. At least TypeScript screamed at me until I fixed that one.

### CODE REVIEW

**Comment by wpoulin** [comment]
Rename the last commit message to match the new title and `Validate Semantic PR` should pass

**Comment by wpoulin** [comment]
Instead of keeping a static list of addresses, I suggest you fetch the addresses from the VaultFactory contract
https://optimistic.etherscan.io/address/0xF65FA202907D6046D1eF33C521889B54BdE08081#readContract

**Comment by Ncookiez** [comment]
> Instead of keeping a static list of addresses, I suggest you fetch the addresses from the VaultFactory contract

I could, but it would never be all-encompassing; it'd be possible to need to input extra addresses there eventually nonetheless.

Just a question before I make that change; should I rename that first commit or is the failing check only referring to whatever the latest commit is?

**Comment by Ncookiez** [comment]
@wpoulin the semantic PR is now passing and it is now querying the `VaultFactory` contract for vault addresses :)

**Review by wpoulin — APPROVED** [review]
Good job and thanks for your contribution

**Pull request merged**
