### PR TITLE
feat(kyberswap-elastic): enable viewing farm elastic on Optimism chain 

### PR DESCRIPTION
**Pull request by linhbkhn95**
## Description

- Enable viewing farm elastic on the Optimism chain 
## Checklist

- [] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

## How to test?
Manual

### CODE REVIEW

**Comment by wpoulin** [comment]
hey gm,
I found the issue and a release containing the fix is on the way, so this PR won't be necessary and I'll close this one out. If anything else comes up you can reach out to me on discord. 
Thanks

**Comment by SamIam-0x** [comment]
Hello @linhbkhn95  - thanks for submitting this! 

qq- do you have an ENS or address you'd want us to attribute this contribution to? We are building out a leaderboard to give credit to users who contributed to Zapper, with potential bonus points of value in the future.

Let me know, thanks!
Sam

**Comment by linhbkhn95** [comment]
Thanks @SamIam-0x 
I don't have ENS yet. But my address is `0x6E3cB6e0658eC9A3B5b966738564fb417E33c930`

**Comment by SamIam-0x** [comment]
that works! thanks!

**Pull request closed without merging**
