### PR TITLE
feat(lyra-newport): Add Lyra Network Integration

### PR DESCRIPTION
**Pull request by paulvaden**
## Description

Add Lyra newport release

## Checklist

- [ x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

## How to test?

0xa5a663b7951dddff89b01194ee16f3af276051c1
0x81ad5e6fa4c085b78ed547125170823e6d2b2478
0x80ece3be489daafb1bc33b1632c03d918c00b32d

### CODE REVIEW

**Comment by wpoulin** [comment]
Updating your last commit message and PR title to something like `feat(lyra-newport): Add Lyra Network Integration` will resolve the issue

**Comment by SamIam-0x** [comment]
hey thanks for adding this @paulvaden !

Smol request after QA'ing - can we update the app slug label from `lyra-newport` to Lyra Newport? Thanks!

**Comment by paulvaden** [comment]
> hey thanks for adding this @paulvaden !
> 
> Smol request after QA'ing - can we update the app slug label from `lyra-newport` to Lyra Newport? Thanks!

How is that done?

**Comment by SamIam-0x** [comment]
I think this actually is fixed by our team, so nevermind!

**Comment by SamIam-0x** [comment]
Hello @paulvaden  - thanks for submitting this! 

qq- do you have an ENS or address you'd want us to attribute this contribution to? We are building out a leaderboard to give credit to users who contributed to Zapper, with potential bonus points of value in the future.

Let me know, thanks!
Sam

**Comment by paulvaden** [comment]
@SamIam-0x Yup you can use muir-lyra.eth, thanks!

**Comment by SamIam-0x** [comment]
Perfect, thanks!

**Pull request merged**
