### PR TITLE
feat(ferro): add ferro app integration with vvs finance refactoring

### PR DESCRIPTION
**Pull request by CronosLabsDev**
### 1. refactor [VVS finance](https://vvs.finance/) to share xVault fetcher

https://github.com/Zapper-fi/studio/commit/5713c88122f3602cf99adfb199b4dca451907c29

* refactor into helpers: `fetchXVaultPositions`, `getXVaultBalances`
* correct `VVS_FINANCE_DEFINITION.groups.xvvsVault.type` to `GroupType.POSITION`

### 2. add [Ferro](https://ferroprotocol.com/) integration

* pool/lp token fetcher (currently only 3FER)
* liquidity staking position fetcher
* xFER token fetcher
* xFER vaults fetcher
  * using refactored helper from VVS finance
* balance fetcher

## Checklist

- [x] I have followed the [Contributing Guidelines](https://github.com/Zapper-fi/studio/blob/edbdd22/CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [x] (optional) As a contributor, my Twitter handle is: https://twitter.com/cronos_labs

## How to test?

1. edit/create `.env` adding `ENABLED_APPS="ferro"`
2. run `pnpm dev` to spin up nest server
3. visit dev endpoints below to see result of fetchers to integrate ferro:
  * http://localhost:5001/apps/ferro/tokens?groupIds[]=pool&network=cronos
  * http://localhost:5001/apps/ferro/positions?groupIds[]=staked-liquidity&network=cronos
  * http://localhost:5001/apps/ferro/tokens?groupIds[]=xfer&network=cronos
  * http://localhost:5001/apps/ferro/positions?groupIds[]=xfer-vault&network=cronos
  * `http://localhost:5001/apps/ferro/balances?addresses[]=<wallet_address>&network=cronos`
  * http://localhost:5001/apps/ferro/tvl?network=cronos

### CODE REVIEW

**Comment by CronosLabsDev** [comment]
### Fetcher results

pool/lp token fetcher (currently only 3FER):

```json
[{"type":"app-token","address":"0x71923713685770d04d69d103008aaffeebc31bde","network":"cronos","appId":"ferro","groupId":"pool","symbol":"3FER-BETA","decimals":18,"supply":67231400.24811836,"price":1.0029427859667501,"pricePerShare":[0.224289975593767,0.34453809245756856,0.4347486782107003],"tokens":[{"id":"315822","networkId":13,"address":"0xf2001b145b43032aaf5ee2884e456ccd805f677d","name":"Dai Stablecoin","symbol":"DAI","decimals":18,"coingeckoId":"dai","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-05-24T13:24:09.986Z","price":1,"totalSupply":"161000000","networkEnumValue":"cronos","type":"base-token","network":"cronos"},{"id":"315763","networkId":13,"address":"0xc21223249ca28397b4b6541dffaecc539bff0c59","name":"USD Coin","symbol":"USDC","decimals":6,"coingeckoId":"usd-coin","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-05-24T13:24:09.986Z","price":1.001,"totalSupply":"835000000","networkEnumValue":"cronos","type":"base-token","network":"cronos"},{"id":"315677","networkId":13,"address":"0x66e428c3f67a68878562e79a0234c1f83c208770","name":"Tether USD","symbol":"USDT","decimals":6,"coingeckoId":"tether","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-05-24T13:24:09.986Z","price":0.9994,"totalSupply":"587000000","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"swapAddress":"0xe8d13664a42b338f009812fa5a75199a865da5cd","liquidity":67477496.4286067,"volume":0,"fee":0.0004},"displayProps":{"label":"DAI / USDC / USDT","secondaryLabel":"22% / 34% / 43%","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0xf2001b145b43032aaf5ee2884e456ccd805f677d.png","https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0xc21223249ca28397b4b6541dffaecc539bff0c59.png","https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x66e428c3f67a68878562e79a0234c1f83c208770.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":67477496.4286067}},{"label":"Supply","value":{"type":"number","value":67231400.24811836}},{"label":"Volume","value":{"type":"dollar","value":0}},{"label":"Fee","value":{"type":"pct","value":0.0004}},{"label":"Ratio","value":"22% / 34% / 43%"}]}}]
```

liquidity staking position fetcher:

```json
[{"type":"contract-position","address":"0xab50fb1117778f293cc33ac044b5579fb03029d0","network":"cronos","appId":"ferro","groupId":"staked-liquidity","tokens":[{"metaType":"supplied","type":"app-token","address":"0x71923713685770d04d69d103008aaffeebc31bde","network":"cronos","appId":"ferro","groupId":"pool","symbol":"3FER-BETA","decimals":18,"supply":67231400.24811836,"price":1.0029427859667501,"pricePerShare":[0.224289975593767,0.34453809245756856,0.4347486782107003],"tokens":[{"id":"315822","networkId":13,"address":"0xf2001b145b43032aaf5ee2884e456ccd805f677d","name":"Dai Stablecoin","symbol":"DAI","decimals":18,"coingeckoId":"dai","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-05-24T13:24:09.986Z","price":1,"totalSupply":"161000000","networkEnumValue":"cronos","type":"base-token","network":"cronos"},{"id":"315763","networkId":13,"address":"0xc21223249ca28397b4b6541dffaecc539bff0c59","name":"USD Coin","symbol":"USDC","decimals":6,"coingeckoId":"usd-coin","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-05-24T13:24:09.986Z","price":1.001,"totalSupply":"835000000","networkEnumValue":"cronos","type":"base-token","network":"cronos"},{"id":"315677","networkId":13,"address":"0x66e428c3f67a68878562e79a0234c1f83c208770","name":"Tether USD","symbol":"USDT","decimals":6,"coingeckoId":"tether","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-05-24T13:24:09.986Z","price":0.9994,"totalSupply":"587000000","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"swapAddress":"0xe8d13664a42b338f009812fa5a75199a865da5cd","liquidity":67477496.4286067,"volume":0,"fee":0.0004},"displayProps":{"label":"DAI / USDC / USDT","secondaryLabel":"22% / 34% / 43%","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0xf2001b145b43032aaf5ee2884e456ccd805f677d.png","https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0xc21223249ca28397b4b6541dffaecc539bff0c59.png","https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x66e428c3f67a68878562e79a0234c1f83c208770.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":67477496.4286067}},{"label":"Supply","value":{"type":"number","value":67231400.24811836}},{"label":"Volume","value":{"type":"dollar","value":0}},{"label":"Fee","value":{"type":"pct","value":0.0004}},{"label":"Ratio","value":"22% / 34% / 43%"}]}},{"metaType":"claimable","id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"poolIndex":1,"liquidity":66426767.75806336,"isActive":true,"dailyROI":0.0011880921704050529,"weeklyROI":0.00831664519283537,"yearlyROI":0.4336536421978443},"displayProps":{"label":"DAI / USDC / USDT","secondaryLabel":{"type":"dollar","value":1.0029427859667501},"images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0xf2001b145b43032aaf5ee2884e456ccd805f677d.png","https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0xc21223249ca28397b4b6541dffaecc539bff0c59.png","https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x66e428c3f67a68878562e79a0234c1f83c208770.png"],"statsItems":[{"label":"APR","value":{"type":"pct","value":43.36536421978443}},{"label":"Liquidity","value":{"type":"dollar","value":66426767.75806336}}]},"key":"2763955882"}]
```

xFER token fetcher:

```json
[{"type":"app-token","address":"0x6b82eace10f782487b61c616b623a78c965fdd88","network":"cronos","appId":"ferro","groupId":"xfer","symbol":"xFER","decimals":18,"supply":25829901.934856597,"price":0.16777775690230415,"pricePerShare":1.0117943150022564,"tokens":[{"id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"liquidity":4333683.007636726,"reserve":26134547.93475369,"exchangeable":false},"displayProps":{"label":"xFER","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"tertiaryLabel":"","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":4333683.007636726}},{"label":"Reserve","value":{"type":"number","value":26134547.93475369}}]}}]
```

xFER vaults fetcher:

```json
[{"type":"contract-position","address":"0xcf3e157e2491f7d739f8923f6ceaa4656e64c92e","network":"cronos","appId":"ferro","groupId":"xfer-vault","tokens":[{"metaType":"supplied","type":"app-token","address":"0x6b82eace10f782487b61c616b623a78c965fdd88","network":"cronos","appId":"ferro","groupId":"xfer","symbol":"xFER","decimals":18,"supply":24308065.008503247,"price":0.16777775690230415,"pricePerShare":1.0117943150022564,"tokens":[{"id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"liquidity":4078352.621762064,"reserve":24594761.98430886,"exchangeable":false},"displayProps":{"label":"xFER","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"tertiaryLabel":"","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":4078352.621762064}},{"label":"Reserve","value":{"type":"number","value":24594761.98430886}}]}},{"metaType":"claimable","id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"poolIndex":0,"liquidity":4045690.6999733998,"isActive":true,"dailyROI":0,"weeklyROI":0,"yearlyROI":0,"isClaimable":false,"poolInfo":{"multiplier":100,"lockPeriod":2592000,"totalStaked":4852953.487063557}},"displayProps":{"label":"1 Months Vault","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"APR","value":{"type":"pct","value":0}},{"label":"Liquidity","value":{"type":"dollar","value":4045690.6999733998}}]}},{"type":"contract-position","address":"0xcf3e157e2491f7d739f8923f6ceaa4656e64c92e","network":"cronos","appId":"ferro","groupId":"xfer-vault","tokens":[{"metaType":"supplied","type":"app-token","address":"0x6b82eace10f782487b61c616b623a78c965fdd88","network":"cronos","appId":"ferro","groupId":"xfer","symbol":"xFER","decimals":18,"supply":24308065.008503247,"price":0.16777775690230415,"pricePerShare":1.0117943150022564,"tokens":[{"id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"liquidity":4078352.621762064,"reserve":24594761.98430886,"exchangeable":false},"displayProps":{"label":"xFER","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"tertiaryLabel":"","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":4078352.621762064}},{"label":"Reserve","value":{"type":"number","value":24594761.98430886}}]}},{"metaType":"claimable","id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"poolIndex":1,"liquidity":4045690.6999733998,"isActive":true,"dailyROI":0,"weeklyROI":0,"yearlyROI":0,"isClaimable":false,"poolInfo":{"multiplier":300,"lockPeriod":15552000,"totalStaked":456972.3609595116}},"displayProps":{"label":"6 Months Vault","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"APR","value":{"type":"pct","value":0}},{"label":"Liquidity","value":{"type":"dollar","value":4045690.6999733998}}]}},{"type":"contract-position","address":"0xcf3e157e2491f7d739f8923f6ceaa4656e64c92e","network":"cronos","appId":"ferro","groupId":"xfer-vault","tokens":[{"metaType":"supplied","type":"app-token","address":"0x6b82eace10f782487b61c616b623a78c965fdd88","network":"cronos","appId":"ferro","groupId":"xfer","symbol":"xFER","decimals":18,"supply":24308065.008503247,"price":0.16777775690230415,"pricePerShare":1.0117943150022564,"tokens":[{"id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"liquidity":4078352.621762064,"reserve":24594761.98430886,"exchangeable":false},"displayProps":{"label":"xFER","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"tertiaryLabel":"","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":4078352.621762064}},{"label":"Reserve","value":{"type":"number","value":24594761.98430886}}]}},{"metaType":"claimable","id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"poolIndex":2,"liquidity":4045690.6999733998,"isActive":true,"dailyROI":0,"weeklyROI":0,"yearlyROI":0,"isClaimable":false,"poolInfo":{"multiplier":600,"lockPeriod":31536000,"totalStaked":357079.18886905024}},"displayProps":{"label":"1 Years Vault","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"APR","value":{"type":"pct","value":0}},{"label":"Liquidity","value":{"type":"dollar","value":4045690.6999733998}}]}},{"type":"contract-position","address":"0xcf3e157e2491f7d739f8923f6ceaa4656e64c92e","network":"cronos","appId":"ferro","groupId":"xfer-vault","tokens":[{"metaType":"supplied","type":"app-token","address":"0x6b82eace10f782487b61c616b623a78c965fdd88","network":"cronos","appId":"ferro","groupId":"xfer","symbol":"xFER","decimals":18,"supply":24308065.008503247,"price":0.16777775690230415,"pricePerShare":1.0117943150022564,"tokens":[{"id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"liquidity":4078352.621762064,"reserve":24594761.98430886,"exchangeable":false},"displayProps":{"label":"xFER","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"tertiaryLabel":"","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":4078352.621762064}},{"label":"Reserve","value":{"type":"number","value":24594761.98430886}}]}},{"metaType":"claimable","id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"poolIndex":3,"liquidity":4045690.6999733998,"isActive":true,"dailyROI":0,"weeklyROI":0,"yearlyROI":0,"isClaimable":false,"poolInfo":{"multiplier":2400,"lockPeriod":126230400,"totalStaked":18446386.24136402}},"displayProps":{"label":"4 Years Vault","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"APR","value":{"type":"pct","value":0}},{"label":"Liquidity","value":{"type":"dollar","value":4045690.6999733998}}]}},{"type":"contract-position","address":"0xcf3e157e2491f7d739f8923f6ceaa4656e64c92e","network":"cronos","appId":"ferro","groupId":"xfer-vault","tokens":[{"metaType":"supplied","type":"app-token","address":"0x6b82eace10f782487b61c616b623a78c965fdd88","network":"cronos","appId":"ferro","groupId":"xfer","symbol":"xFER","decimals":18,"supply":24308065.008503247,"price":0.16777775690230415,"pricePerShare":1.0117943150022564,"tokens":[{"id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"liquidity":4078352.621762064,"reserve":24594761.98430886,"exchangeable":false},"displayProps":{"label":"xFER","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"tertiaryLabel":"","images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"Liquidity","value":{"type":"dollar","value":4078352.621762064}},{"label":"Reserve","value":{"type":"number","value":24594761.98430886}}]}},{"metaType":"claimable","id":"3518175","networkId":13,"address":"0x39bc1e38c842c60775ce37566d03b41a7a66c782","name":"FerroToken","symbol":"FER","decimals":18,"coingeckoId":"ferro","status":"approved","hide":false,"canExchange":true,"updatedAt":"2022-07-07T07:43:13.187Z","createdAt":"2022-06-22T10:00:14.696Z","price":0.165822,"totalSupply":"4318775808.003600360035973889","networkEnumValue":"cronos","type":"base-token","network":"cronos"}],"dataProps":{"poolIndex":4,"liquidity":4045690.6999733998,"isActive":true,"dailyROI":0,"weeklyROI":0,"yearlyROI":0,"isClaimable":true},"displayProps":{"label":"Pending Vault Reward","secondaryLabel":{"type":"dollar","value":0.16777775690230415},"images":["https://storage.googleapis.com/zapper-fi-assets/tokens/cronos/0x39bc1e38c842c60775ce37566d03b41a7a66c782.png"],"statsItems":[{"label":"APR","value":{"type":"pct","value":0}},{"label":"Liquidity","value":{"type":"dollar","value":4045690.6999733998}}]}}]
```

tvl:

```json
{"appId":"ferro","appName":"Ferro","network":"cronos","tvl":71811179.43624343}
```

**Comment by CronosLabsDev** [comment]
@immasandwich sorry for the wait, please take a look for this integration 🙏

**Comment by immasandwich** [comment]
Hey @CronosLabsDev , we're having some issues with our Cronos nodes with regards to rate limits and traffic. We're working with the RockX team to get RPCs that can successfully sustain our traffic. I'll need to hold off on getting this PR in for a little while longer. Terribly sorry for the delays here 🙏

**Comment by SamIam-0x** [comment]
Hello @CronosLabsDev !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by SamIam-0x** [comment]
Gentle ping on the above comment @CronosLabsDev !

**Comment by CronosLabsDev** [comment]
Hello Sam!

Happy to comply, here is our protocol treasury wallet address: `0xe13570350a704774AC5f04728E2E631589B4740C`
Let us if anything needed on our side!

cc @SamIam-0x

**Comment by CronosLabsDev** [comment]
for @immasandwich, have rebased and updated the code change here to make sure they works, is the [cronos RPC node issue](https://github.com/Zapper-fi/studio/pull/858#issuecomment-1189206243) resolved? if so please take a look of the change here.
Thank you 🙏

**Comment by SamIam-0x** [comment]
> for @immasandwich, have rebased and updated the code change here to make sure they works, is the [cronos RPC node issue](https://github.com/Zapper-fi/studio/pull/858#issuecomment-1189206243) resolved? if so please take a look of the change here. Thank you 🙏

Hey there-- apologies for the delay. We're working through issues we are running into with Cronos RPC rate limiting. We think we may have a solution, but not quite sure. Will keep you updated!

**Comment by CronosLabsDev** [comment]
got it, thanks for the update @SamIam-0x 🙏

**Comment by SamIam-0x** [comment]
> got it, thanks for the update @SamIam-0x 🙏

FYI Cronos should be back in business! However, @immasandwich may help with refactoring the code, as we recently changed to templates.

**Comment by CronosLabsDev** [comment]
hello @SamIam-0x @immasandwich 😃 
any update on this one? is there any change needed here? 🙏

**Comment by immasandwich** [comment]
Hey @CronosLabsDev , we've been having a lot of downtime on Cronos since launching support for the chain. As such, we've turned off integration on Zapper until we can find a way to stabilize our calls to Cronos RPCs... unfortunately, both public RPC nodes and paid RPC nodes (with RockX) have been unable to provide good up-time.. if you have any suggestions, please let us know!

**Pull request closed without merging**
