### PR TITLE
feat(llama-airforce): Support uCVX pounder and claims

### PR DESCRIPTION
**Pull request by 0xAlunara**
## Description

This PR adds support for the uCVX pounder & merkle distributor claims for https://llama.airforce.

I have been unable to get Zapper Studio working on my dev machine due to being forced to lower version of NodeJS, which does not work with Zapper Studio. Therefore, I have been unable to properly test this PR. I've done the best I can with what I think should be done to add uCVX support.

The uCVX claim contract is very similar to the uCRV and uFXS claim contracts, except (what is relevant to us) `underlying()` has been renamed to `asset()` and `totalUnderlying()` is renamed to `totalAssets()`. I copied the typechain generated contracts from my local source at Llama Airforce.

### CODE REVIEW

**Comment by immasandwich** [comment]
Hey @0xAlunara , you can test locally by using `nvm` so you can install multiple versions of Node and switch between them: https://github.com/nvm-sh/nvm

I'll give this a quick test and then ship it.

**Comment by SamIam-0x** [comment]
Hello @0xAlunara !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by 0xAlunara** [comment]
Ah, sure. I've added our treasury address, will do so in future PRs as well.

**Comment by SamIam-0x** [comment]
> 

wonderful! thanks!

**Pull request merged**
