### PR TITLE
feat(coslend): add coslend app integration

### PR DESCRIPTION
**Pull request by coslendteam**
## Description

add [coslend](https://coslend.com) app integration

- supply (token) fetcher and cache manager
- borrow contract position fetcher
- balance fetcher
- TVL fetcher

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [x] (optional) As a contributor, my Twitter handle is: https://twitter.com/coslend

## How to test?

1. edit/create .env adding ENABLED_APPS="coslend"
2. run pnpm dev to spin up nest server
3. visit dev endpoints below to see result of fetchers to integrate coslend:

- http://localhost:5001/apps/coslend/tokens?network=evmos&groupIds[]=supply
- http://localhost:5001/apps/coslend/positions?network=evmos&groupIds[]=borrow
- http://localhost:5001/apps/coslend/tvl?network=evmos
- http://localhost:5001/apps/coslend/balances?network=evmos&addresses[]=<wallet_address>

### CODE REVIEW

**Comment by immasandwich** [comment]
Hello @coslendteam ! Integration looks great, but you could actually use the `CompoundAppModule` as an `import` and use the helpers directly from the Compound application, rather than copying over the helpers. This would drop the amount of copy-pasta.

I see that there's some differences between the `compound.supply.token-helper.ts` and `coslend.supply.token-helper.ts`, but you can definitely adjust the `compound.supply.token-helper.ts` to include an `oracle` parameter optionally for resolving tokens that are not found in Zapper's base tokens.

Does that make sense? Feel free to swing by Discord for a quicker discussion pace.

**Comment by coslendteam** [comment]
> Hello @coslendteam ! Integration looks great. I would suggest that you use import the `CompoundAppModule` as an in the `imports` array of the module, and use the helpers directly from the Compound app directory, rather than copying over the helpers. This would drop the amount of copy-pasta.
> 
> I see that there's some differences between the `compound.supply.token-helper.ts` and `coslend.supply.token-helper.ts`, but you can definitely adjust the `compound.supply.token-helper.ts` to include an `oracle` parameter optionally for resolving tokens that are not found in Zapper's base tokens.
> 
> Does that make sense? Feel free to swing by Discord for a quicker discussion pace.

Our APY calculation is different, it is based on second, not block, the ABI has also changed, further, we may add more difference to update our app, so we suggest don't use compound helper directly.

**Comment by SamIam-0x** [comment]
Hello @coslendteam !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by SamIam-0x** [comment]
Gentle ping on the above @coslendteam !

**Pull request merged**
