### PR TITLE
feat: add lido integration

### PR DESCRIPTION
**Pull request by rkolpakov**
## Description

Add Lido integration for stETH/wstETH tokens.

## Checklist

- [x] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)

## How to test?

http://localhost:5001/apps/lido/tvl
http://localhost:5001/apps/lido/tokens?groupIds[]=steth&network=ethereum
http://localhost:5001/apps/lido/tokens?groupIds[]=wsteth&network=ethereum
http://localhost:5001/apps/lido/balances?addresses[]=0x3e40d73eb977dc6a537af587d48316fee66e9c8c&network=ethereum

### CODE REVIEW

**Comment by immasandwich** [comment]
Hey @rkolpakov, we already support stETH and wstETH as `BaseToken` types (i.e.: you'll see them both listed [here](https://api.zapper.fi/v1/prices?api_key=96e0cc51-a62e-42ca-acee-910ea7d2a241)). What's the purpose of listing them here instead as `AppToken` types? (no complaints, just want to understand the reasoning... is it to show the underlying ETH balance for stETH and wstETH?)

**Comment by rkolpakov** [comment]
Hey @immasandwich. Thanks for taking a look at the PR. 
I followed the integration guideline so I thought that token fetcher is a mandatory thing for making everything around this token work. If it's not, we can completely remove it.
What do you think about TVL and balance fetchers? Are they OK or need to be improved?

**Comment by SamIam-0x** [comment]
Hello @rkolpakov !

Looks like you did not provide an address when submitting your PR. I recognize it may have seemed kind of random that we were asking for a wallet address with a PR submission, but we are actually looking for ways to reward Studio contributors in the future. 

Is there an address you’d want to provide? Could even be an empty address, if you do not have an doxxed address

Let me know! Also, if you’d like to privately provide it, feel free to shoot me a TG https://t.me/SamIAm_0x or DM on the Zapper Discord.

Thanks!
Sam

**Comment by SamIam-0x** [comment]
Gentle ping on this @rkolpakov ! This is a real message that is not some bot!

**Pull request merged**
