### PR TITLE
feat(goldfinch): Add Senior Pool Withdrawal requested fidu and claima…

### PR DESCRIPTION
**Pull request by gregegan**
Add support for SeniorPool withdrawal requests

image

image

## Checklist

- [ ] I have followed the [Contributing Guidelines](../CONTRIBUTING.md)
- [ ] (optional) As a contributor, my Ethereum address/ENS is:
- [ ] (optional) As a contributor, my Twitter handle is:

### CODE REVIEW

**Review by wpoulin — APPROVED** [review]
Excellent ! ✅

**Comment by SamIam-0x** [comment]
Hello @gregegan  - thanks for submitting this! 

qq- do you have an ENS or address you'd want us to attribute this contribution to? We are building out a leaderboard to give credit to users who contributed to Zapper, with potential bonus points of value in the future.

Let me know, thanks!
Sam

**Comment by gregegan** [comment]
> Hello @gregegan - thanks for submitting this!
> 
> qq- do you have an ENS or address you'd want us to attribute this contribution to? We are building out a leaderboard to give credit to users who contributed to Zapper, with potential bonus points of value in the future.
> 
> Let me know, thanks! Sam

gregan.eth

**Comment by SamIam-0x** [comment]
Thanks!

**Pull request merged**
